# Generated by Django 4.2.6 on 2023-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
